name: pawsight
description: "A companion app for pet owners to interpret body language with offline library and AI chat."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  font_awesome_flutter: ^10.12.0
  forui: ^0.16.0
  http: ^1.6.0
  image_picker: ^1.2.1
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
